<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>CinemaApp.DAL</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CinemaApp.DAL\CinemaApp.DAL.csproj" />
      <ProjectReference Include="..\CinemaApp.Data\CinemaApp.Data.csproj" />
    </ItemGroup>

</Project>
